# Generated by Django 4.0.2 on 2022-08-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('auto_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=20)),
                ('nick_name', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('contact_number', models.CharField(max_length=10, null=True)),
                ('about', models.TextField(null=True)),
                ('company_name', models.CharField(max_length=30, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('rating_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='question_model',
            fields=[
                ('auto_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=100)),
                ('question_description', models.TextField()),
                ('technology_name', models.CharField(max_length=20)),
                ('status_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_question', models.ManyToManyField(to='QA_App.user_model')),
            ],
            options={
                'ordering': ('auto_question_id',),
            },
        ),
        migrations.CreateModel(
            name='answer_model',
            fields=[
                ('auto_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_and_dislike', models.IntegerField(null=True)),
                ('technology_name', models.CharField(max_length=20)),
                ('status_name', models.CharField(max_length=20)),
                ('questions_answers', models.ManyToManyField(to='QA_App.question_model')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA_App.user_model')),
            ],
            options={
                'ordering': ('auto_answer_id',),
            },
        ),
    ]
