# Generated by Django 4.0 on 2022-07-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20, null=True)),
                ('user_profile', models.ImageField(upload_to='')),
                ('contact_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('about', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=30, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
