# Generated by Django 4.0.2 on 2022-09-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_like_value_model',
            name='answer_like',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.answer_model'),
        ),
        migrations.AlterField(
            model_name='question_like_value_model',
            name='question_like',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.question_model'),
        ),
    ]
