# Generated by Django 4.0.2 on 2022-09-09 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_answer_like_value_model_answer_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_like_value_model',
            name='question_like',
        ),
        migrations.AddField(
            model_name='answer_model',
            name='answer_likes',
            field=models.ManyToManyField(related_name='user_answers_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_model',
            name='question_likes',
            field=models.ManyToManyField(related_name='user_questions_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='answer_like_value_model',
        ),
        migrations.DeleteModel(
            name='question_like_value_model',
        ),
    ]
