# Generated by Django 4.0.2 on 2022-10-11 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_question_like_value_model_question_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_model',
            name='answer_likes',
            field=models.ManyToManyField(blank=True, related_name='user_answers_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question_model',
            name='question_likes',
            field=models.ManyToManyField(blank=True, related_name='user_questions_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
