# Generated by Django 4.0 on 2022-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='username1',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
