# Generated by Django 4.0 on 2022-07-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usermodel_username1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='username1',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
