# Generated by Django 4.0 on 2022-07-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_username1_usermodel_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.IntegerField(null=True)),
                ('rating_name', models.CharField(max_length=30, null=True)),
                ('usermodel_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='accounts.usermodel')),
            ],
        ),
    ]
