# Generated by Django 4.0.6 on 2022-07-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usermodel_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
