# Generated by Django 4.0.6 on 2022-07-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_usermodel_email_remove_usermodel_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='contact_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
