# Generated by Django 4.0.6 on 2022-07-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usermodel_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_profile',
        ),
    ]
